export default {
  DETECT: 0,
  START_INSPECT_CANVAS: 1,
  END_INSPECT_CANVAS: 2,
  IS_KARAS_CANVAS: 3,
  START_INSPECT_ELEMENT: 4,
  END_INSPECT_ELEMENT: 5,
  INIT_ROOT_JSON: 6,
  TAB_UPDATE: 7,
  MOUSE_ENTER_ELEMENT: 8,
  MOUSE_LEAVE_ELEMENT: 9,
  CLICK_ELEMENT: 10,
};
